export { createPrismaClient, prisma } from "./client";
export { Prisma, PrismaClient } from "./generated/prisma/client";
export type {
  AddOnService,
  AuditLog,
  Carrier,
  CarrierActivationRule,
  Customer,
  CustomerMemo,
  DeviceModel,
  DiscountPolicy,
  InventoryColorOption,
  InventoryItem,
  ManualSchedule,
  Payment,
  RatePlan,
  Receivable,
  Sale,
  SaleAddOn,
  SaleProfitPolicy,
  SalesAgency,
  Session,
  StaffCommissionPolicy,
  Store,
  User,
} from "./generated/prisma/client";
